/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analyser;

import java.awt.FileDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FirstWindow extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
            FileDialog fdlg = new FileDialog(this, "Open file", 
            FileDialog.LOAD);
             String FileName = new String();
             String FileNameExeption = new String();
             int metod=0,m=0,n=0;
             boolean flagStem=false
                     ,flagLemma=false
                     ,flagStopSlova=false
                     ,flagPredloj=false
                     ,flagNeu4it4R=false
                     ,flagOpred4R=false
                     ,flagU4it4R=false
                     ,flagOknoMN=false
                     ,flagON=true;
             
             
    /**
     * Creates new form FirstWindow
     */
    public FirstWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jButton1.setText("Open File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Open exeption file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Begin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Алгоритм расчета силы связи", "Алгоритм расчета силы связи с учетом частей речи" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Предобработка");

        jCheckBox1.setText("Стоп-слова");

        jCheckBox2.setText("Стемминг");

        jCheckBox3.setText("Лемматизация");

        jLabel2.setText("Формирование словаря КС");

        jCheckBox4.setText("Выделение предложений");
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });

        jCheckBox5.setText("Выделение по окну MxN");
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });

        jTextField3.setText("2");

        jTextField4.setText("2");

        jLabel3.setText(" M = ");

        jLabel4.setText(" N = ");

        jLabel5.setText("Работа с частью речи");

        jCheckBox6.setText("Не учитывать части речи");
        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
        });

        jCheckBox7.setText("Определять часть речи");
        jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox7MouseClicked(evt);
            }
        });

        jCheckBox8.setText("Учитывать часть речи");
        jCheckBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel5)))
                                .addGap(203, 203, 203))
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 203, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void getParam(){
    
        if (jCheckBox1.isSelected()){this.flagStopSlova=true;}
        if (jCheckBox2.isSelected()){this.flagStem=true;}
        if (jCheckBox3.isSelected()){this.flagLemma=true;}
        if (jCheckBox4.isSelected()){this.flagPredloj=true;}
        if (jCheckBox5.isSelected()){this.flagOknoMN=true;}
        if (jCheckBox6.isSelected()){this.flagNeu4it4R=true;}
        if (jCheckBox7.isSelected()){this.flagOpred4R=true;}
        if (jCheckBox8.isSelected()){this.flagU4it4R=true;}
        
        if (!jCheckBox1.isSelected()){this.flagStopSlova=false;}
        if (!jCheckBox2.isSelected()){this.flagStem=false;}
        if (!jCheckBox3.isSelected()){this.flagLemma=false;}
        if (!jCheckBox4.isSelected()){this.flagPredloj=false;}
        if (!jCheckBox5.isSelected()){this.flagOknoMN=false;}
        if (!jCheckBox6.isSelected()){this.flagNeu4it4R=false;}
        if (!jCheckBox7.isSelected()){this.flagOpred4R=false;}
        if (!jCheckBox8.isSelected()){this.flagU4it4R=false;}
    }
    public boolean getON(){return this.flagON;}
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       this.metod=this.jComboBox1.getSelectedIndex(); // TODO add your handling code here:
       if (this.metod==0){
       jCheckBox4.setSelected(true);
       jCheckBox6.setSelected(true);
       jCheckBox5.setSelected(false);
       jCheckBox5.setEnabled(false);
       }
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
if (jComboBox1.getSelectedIndex()==0){

jCheckBox1.setEnabled(true);
jButton2.setEnabled(false);
jTextField2.setEnabled(false);
jCheckBox2.setEnabled(true);
jCheckBox3.setEnabled(true);

jCheckBox4.setEnabled(true);
jCheckBox5.setEnabled(false);
jTextField3.setEnabled(false);
jTextField4.setEnabled(false);

jCheckBox6.setEnabled(true);
jCheckBox7.setEnabled(true);
jCheckBox8.setEnabled(true);


} 
if (jComboBox1.getSelectedIndex()==1){

jCheckBox1.setEnabled(true);
jButton2.setEnabled(false);
jTextField2.setEnabled(false);
jCheckBox2.setEnabled(true);
jCheckBox3.setEnabled(true);

jCheckBox4.setEnabled(false);
jCheckBox5.setEnabled(true);
jTextField3.setEnabled(false);
jTextField4.setEnabled(false);

jCheckBox6.setEnabled(false);
jCheckBox7.setEnabled(true);
jCheckBox8.setEnabled(true);

jCheckBox5.setSelected(true);
jCheckBox7.setSelected(true);
jCheckBox8.setSelected(true);
} 

if (jCheckBox1.isSelected()&jCheckBox1.isEnabled()){
jButton2.setEnabled(true);
jTextField2.setEnabled(true);    
}
if (!jCheckBox1.isSelected()|!jCheckBox1.isEnabled()){
jButton2.setEnabled(false);
jTextField2.setEnabled(false);
}

if (jCheckBox5.isSelected()&jCheckBox5.isEnabled()){
jTextField3.setEnabled(true);
jTextField4.setEnabled(true); 
this.m=Integer.valueOf(this.jTextField3.getText());
this.n=Integer.valueOf(this.jTextField4.getText());   
}
if (jCheckBox5.isSelected()==false|jCheckBox5.isEnabled()==false){
jTextField3.setEnabled(false);
jTextField4.setEnabled(false);
}

    // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
    if (jCheckBox4.isSelected()&jCheckBox4.isEnabled()){
jCheckBox5.setSelected(false);
}   // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
    if (jCheckBox5.isSelected()&jCheckBox5.isEnabled()){
jCheckBox4.setSelected(false);
}    // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked
     if (jCheckBox6.isSelected()&jCheckBox6.isEnabled()){
jCheckBox7.setSelected(false);
jCheckBox8.setSelected(false);
}   // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6MouseClicked

    private void jCheckBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MouseClicked
     if (jCheckBox7.isSelected()&jCheckBox7.isEnabled()){
jCheckBox6.setSelected(false);
}   // TODO add your handling code here:
     if (jComboBox1.getSelectedIndex()==1){
     jCheckBox7.setSelected(true);
jCheckBox8.setSelected(true);
     }
    }//GEN-LAST:event_jCheckBox7MouseClicked

    private void jCheckBox8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox8MouseClicked

if (jCheckBox8.isSelected()&jCheckBox8.isEnabled()){
jCheckBox7.setSelected(true);
jCheckBox6.setSelected(false);
}    
     if (jComboBox1.getSelectedIndex()==1){
     jCheckBox7.setSelected(true);
jCheckBox8.setSelected(true);
     }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
fdlg.show();
  FileName=(fdlg.getDirectory() + fdlg.getFile());
  jTextField1.setText(FileName);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
fdlg.show();
  FileNameExeption=(fdlg.getDirectory() + fdlg.getFile());
  jTextField2.setText(FileNameExeption);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.getParam();
if (FileName.length()>2){
if ((FileNameExeption.length()>2 & flagStopSlova==true)|flagStopSlova==false )
{
SecondWindow window2 = new SecondWindow();

window2.SetParamWindow(FileName, FileNameExeption, 
        flagStem, flagLemma, flagStopSlova,
        flagPredloj, flagNeu4it4R, flagOpred4R, 
        flagU4it4R, flagOknoMN,metod,m,n);
  window2.main();

this.setVisible(false);
this.setEnabled(false);
    
}
}

if (FileName.length()<2){
//JOptionPane.showMessageDialog( " НЕ ВЫБРАН ФАЙЛ ТЕКСТА ДЛЯ ОБРАБОТКИ!!! ВЫБЕРИТЕ ФАЙЛ. ");
JOptionPane.showConfirmDialog(this," НЕ ВЫБРАН ФАЙЛ ТЕКСТА ДЛЯ ОБРАБОТКИ!!! ВЫБЕРИТЕ ФАЙЛ.");

//JOptionPane.showInternalConfirmDialog(" НЕ ВЫБРАН ФАЙЛ ТЕКСТА ДЛЯ ОБРАБОТКИ!!! ВЫБЕРИТЕ ФАЙЛ.");
}
if (FileNameExeption.length()<2 & flagStopSlova==true){
//JOptionPane.showMessageDialog(this,evt , " НЕ ВЫБРАН ФАЙЛ СТОП-СЛОВ!!! ВЫБЕРИТЕ ФАЙЛ. ", 0);
JOptionPane.showConfirmDialog(this," НЕ ВЫБРАН ФАЙЛ СТОП-СЛОВ!!! ВЫБЕРИТЕ ФАЙЛ. ");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    }    
    
      public void getParamWindow(String FileName,
             String FileNameExeption,
                    boolean flagStem,
                    boolean flagLemma,
                    boolean flagStopSlova,
                    boolean flagPredloj,
                    boolean flagNeu4it4R,
                    boolean flagOpred4R,
                    boolean flagU4it4R,
                    boolean flagOknoMN){
               
             FileName = this.FileName;
             FileNameExeption = this.FileNameExeption;
             flagStem=this.flagStem;
             flagLemma=this.flagLemma;
             flagStopSlova=this.flagStopSlova;
             flagPredloj=this.flagPredloj;
             flagNeu4it4R=this.flagNeu4it4R;
             flagOpred4R=this.flagOpred4R;
             flagU4it4R=this.flagU4it4R;
             flagOknoMN=this.flagOknoMN;
    
    }
    /**
     * @param args the command line arguments
     */
    public  void main() {
        jCheckBox4.setSelected(true);
        jCheckBox6.setSelected(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
